### ISSUE TITLE
Mediation Support for Facebook, Ironsouce, etc

### ISSUE THREAD

**Issue by ghost** [Poing-Studios/godot-admob-plugin#23] opened 2022-03-04 00:36 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gumaciel** [comment] 2022-03-10 20:59
Thanks for the suggestion, there is already an Issue for this: https://github.com/Poing-Studios/godot-admob-android/issues/28

I'm currently checking how we can do this part of mediation, the idea is to be able to add as many mediations as possible in AdMob, but the problem is how to do it with Godot and Plugins

I'm not going to close this issue because, in addition to making changes to the android/ios plugins repository, we'll probably also make changes to the editor to dynamically download mediations

**Comment by hani09876** [comment] 2022-03-19 17:33
> Thanks for the suggestion, there is already an Issue for this: https://github.com/Poing-Studios/godot-admob-android/issues/28
> 
> I'm currently checking how we can do this part of mediation, the idea is to be able to add as many mediations as possible in AdMob, but the problem is how to do it with Godot and Plugins
> 
> I'm not going to close this issue because, in addition to making changes to the android/ios plugins repository, we'll probably also make changes to the editor to dynamically download mediations

Sir . Did you added Facebook ads

**Comment by gumaciel** [comment] 2022-03-31 01:06
Not yet, sorry it can take some months to be completed

**Comment by gumaciel** [comment] 2023-06-20 23:16
Closing since it was done on #82, development is finished but need to test.

Currently it's only supporting `Vungle (Liftoff Monetize)`, `Meta` and `AdColony` for [Android](https://github.com/Poing-Studios/godot-admob-android/issues/167).

Check the future status of iOS here: https://github.com/Poing-Studios/godot-admob-ios/issues/45

**Closed by gumaciel** 2023-06-20 23:16 UTC
Labels: enhancement
