### ISSUE TITLE
Error after debugging process

### ISSUE THREAD

**Issue by javrocks** [Poing-Studios/godot-admob-plugin#97] opened 2023-08-29 09:14 UTC
### Godot version

3.5

### Plugin version

v1.3.4

### System information

Windows 11

### Phone information, if applicable

iPhone 11 

### Issue description

After the game stops running and the debug process has ended, Godot starts spamming this error and i don't know why.

![image](https://github.com/Poing-Studios/godot-admob-plugin/assets/143153420/e9168ba5-2ee1-4e5c-8283-56fdbfc65602)

### Steps to reproduce

no steps

**Comment by gumaciel** [comment] 2023-08-29 11:07
@javrocks this happens after you debug for iOS? You started on Xcode or Godot?

Try to run with and without the plugin

I think the only reason for this to happen is that sometimes the Plugin makes a request to this address: https://gist.github.com/gumaciel/ba15bd85ebcc87866c24a819de37cc9a and it may be limiting.

Can you provide more information?

**Comment by javrocks** [comment] 2023-08-29 12:36
Im running on godot Windows, and when i run the game i don't see the errors but when i close the game, godot start's spamming those errors
However when i remove the plugin ver 1.3.4 from my root folder i don't see any errors, so i believe it's the plugin

**Comment by gumaciel** [comment] 2023-08-29 13:30
I will investigate this, thank you, have you opened the "AdMob" editor page multiple times? Or not?

**Comment by javrocks** [comment] 2023-08-29 13:41
I think i opened it multiple times 
To open the Admob editor i go to Project settings, then Plugins then enable it. Then i open it by clicking the Admob icon next to AssetLib.
Also when i'm ready to release to a Appstore do i need to change something, cus Is Real is already checked?

**Comment by gumaciel** [comment] 2023-08-29 13:43
When you export your game to App Store or Google Play, **don't** mark `debug_on_release` and **mark** `is_real`

**Comment by javrocks** [comment] 2023-08-29 13:46
Ok cool, 
Was i suppose to mark debug_on_release when i was testing cus i didn't. If not what is debug on release for ?

**Comment by gumaciel** [comment] 2023-08-29 14:36
`debug_on_release` is to force test on TestFlight or something else

**Comment by gumaciel** [comment] 2023-09-06 22:31
@javrocks just tested here, and this error doesn't happen with me on Godot 3.5.2, can you try it again?

**Comment by javrocks** [comment] 2023-09-06 23:10
I use Godot 3.5 and ios-template 3.5.2 and After further testing it seems this error happens when the Godot app isn't closed properly. It seems the only way to stop this error for me, is to take the plugin out of the root folder, run the game without the plugin, then put the plugin back in the root folder and run it with the plugin. Idk if that solves the issue but When i do that i don't see the errors getting spammed

**Comment by javrocks** [comment] 2023-09-07 01:51
No it doesn't happen when i run the game, it happens after i run and close the game. I don't see the error currently cus as u said i deleted the plugin and added it again, but i think if i shut my laptop screen down while godot is open the errors are gonna come back.

**Comment by gumaciel** [comment] 2023-09-07 15:10
I believe that this error is not caused specifically by the plugin, but by the Node HTTPRequest when it is requested many times for `gist.github`, it could even be some failure in your internet connection.

I will be closing the Issue as it looks like we can't fix it, If you have more details on how to reproduce this issue feel free to write here

**Closed by gumaciel** 2023-09-07 15:10 UTC
Labels: bug

**Comment by javrocks** [comment] 2023-09-07 19:12
Alright
