### ISSUE TITLE
AdMobEditor node it null in some tabs

### ISSUE THREAD

**Issue by fakhris** [Poing-Studios/godot-admob-plugin#86] opened 2023-08-12 20:38 UTC
### Godot version

4.1.1

### Plugin version

1.0.0

### System information

any

### Issue description

I installed the plugin from Assetlib on Godot 4.1.1. In some tabs the node the following statement cannon get the node because it is not parent.
`@onready var AdMobEditor : Control = find_parent("AdMobEditor")`
 I printed the parents using get_path() and AdMobEditor is not in the path so it returns null and cause many issues.

### Steps to reproduce

1- Go to the plugin UI
2- Go to Banner tab and save it will save any thing

**Comment by fakhris** [comment] 2023-08-12 20:39
sorry, I installed the plugin from Assetlib on Godot 4.1.1 not 4.0.1

**Comment by gumaciel** [comment] 2023-08-13 15:22
hi @fakhris , sorry, but I couldn't reproduce it, can you show the "output" to see what error happens?

what scripts does this bug happen?

**Comment by fakhris** [comment] 2023-08-14 11:51
Hi the main problem is that some tabs like banner tab is not saving.

**Comment by gumaciel** [comment] 2023-08-14 18:18
I could identify the problem, this error is common if you are going to edit the scene because it doesn't really exist, but on the editor screen it doesn't happen

About the banner not saving, I just solved it in https://github.com/Poing-Studios/godot-admob-plugin/commit/7a68a8168b4b750d8cffa3cb6d8a226b64eedf73, soon I will release a new version

**Comment by gumaciel** [comment] 2023-08-15 02:43
@fakhris This should be fixed on: https://github.com/Poing-Studios/godot-admob-plugin/releases/tag/v2.0.0

Please test it

**Comment by gumaciel** [comment] 2023-08-24 12:17
Closing because it seems to be solved

**Closed by gumaciel** 2023-08-24 12:17 UTC
Labels: bug
